apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ppatierno/rhte-mysql:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_USER
            value: mysqluser
          - name: MYSQL_PASSWORD
            value: mysqlpw
          - name: MYSQL_ROOT_PASSWORD
            value: debezium
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 33060
          name: mysqlex
          protocol: TCP
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
      volumes:
        - emptyDir: {}
          name: mysql-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: mysqlex
    port: 33060
    protocol: TCP
    targetPort: mysqlex
type: ClusterIP

          
